#! /Users/songli/anaconda3/bin/python
import subprocess
import sys

if __name__ == '__main__':
    args = sys.argv
    on_list = ['ON', 'on', '1', 'On']
    off_list = ['OFF', 'off', '0', 'Off']
    if len(args) != 2 or args[1] not in on_list + off_list:
        print("Usage: powerMode [ON/on/On/1/OFF/off/Off/0]")
    else:
        if args[1] in on_list:
            subprocess.call('sudo pmset -a lowpowermode 1', shell=True)
        else:
            subprocess.call('sudo pmset -a lowpowermode 0', shell=True)
    