#! /Users/songli/anaconda3/bin/python
import os
import sys
import subprocess

def main():
    args = sys.argv
    if len(args) != 2:
        print("Usage: pysh 'python commands'")
        return 
    command = args[1]
    if "=" not in command:
        print("Unsupported python command")
        return
    subs = command.replace(" ", "").split("=")
    var = subs[0]
    val = subs[1]
    os.system(f"{var}={val}")
    return

if __name__ == "__main__":
    main()