#! /Users/songli/anaconda3/bin/python
import os
import sys

if __name__ == '__main__':
    args = sys.argv
    if len(args) != 2:
        print("Usage: strlen str")
    else:
        print(f"{len(args[1])}")